management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,env

spring:
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    urls:
      - name: v1
        url: spec-crowdproj-vote-v1.yaml
sql:
  url: "jdbc:postgresql://localhost:5432/vote"
  user: postgres
  password: postgres
  schema: vote

#sql:
#  url: ${SQL_URL:jdbc:postgresql://localhost:5432/vote?autoReconnect=true"&"useSSL=false }
#  user: ${SQL_USER:postgres}
#  password: ${SQL_PASSWORD:postgres}
#  schema: ${SQL_SCHEMA:vote}
#  drop-database: ${SQL_DROP_DATABASE:false}
#  fast-migration: ${SQL_FAST_MIGRATION:true}
